### PR TITLE
Remove as_type.cl since it is now defined as macros in opencl-c.h

### PR DESCRIPTION
**Pull request by yxsamliu**

### CODE REVIEW

**Comment by whchung** [comment]
@yxsamliu may I understand the working commit of llvm/clang to build ROCm-Device-Libs based on this PR?

**Comment by whchung** [comment]
@gregrodgers could you manually fetch this PR and see if this fixes issues you are seeing? If possible I'd like to understand the working llvm/clang commit to build ROCm-Device-Libs based on this PR.

**Comment by yxsamliu** [comment]
f3f636b7d3fa692036026e064738c0521ce035ad of clang

**Comment by gregrodgers** [comment]
I tested and the opencl library now compiles cleanly with this update.

**Pull request merged**
