### PR TITLE
installing other required headers for device enqueue

### PR DESCRIPTION
**Pull request by ashwinma**

### CODE REVIEW

**Comment by b-sumner** [comment]
If this is something we will want post 1.5, I'd rather see the change made to gerrit master and then merged into 1.5.

**Comment by ashwinma** [comment]
1) We definitely need this if we have to use your updates to ockl. So, it should be part of this release as a fix/patch I suppose.
2) How do I make a commit to gerrit master?

**Comment by b-sumner** [comment]
Follow the steps here: http://git.amd.com/gerrit/step_by_step.html .  Once the change is verified and approved I will submit it.

**Comment by ashwinma** [comment]
Done.

**Pull request closed without merging**
