### PR TITLE
Add clock functions in CL

### PR DESCRIPTION
**Pull request by guansong**
I also have a question on this, the memrealtime returns the cycle? 
Do we have a way to get the frequency of the gpu? So the real time can be computed?

### CODE REVIEW

**Comment by b-sumner** [comment]
memrealtime reads a fixed rate clock, not the cycle counter.  Its frequency varies.  I believe you can get some information about it from the ROC/HSA runtime.  On discrete GPUs I think it runs in the tens of MHz.

**Comment by guansong** [comment]
Ok, thanks. I double checked the usage of the function from OpenMP runtime, it is the same as the cuda one, both needs to factor by a TICK to get the real time. So I dropped GCN prefix and please approve it and merge in.

**Comment by whchung** [comment]
@guansong I've just merged this PR. Due to changes of address space mapping in the backend, I would recommend you keep as little handcrafted LLVM IR as possible. If possible keep your implementation in OpenCL would always get you correct IR produced by the frontend.

**Comment by guansong** [comment]
Yes, that is the Brian's suggestion as well. For things difficult to do, Greg decide to move those in yet another location.

**Pull request merged**
