### PR TITLE
Rewrite SMID as requested

### PR DESCRIPTION
**Pull request by guansong**

### CODE REVIEW

**Comment by guansong** [comment]
The layout is still there. Changed the HW_REGISTER_ID name to HW_ID.

**Comment by guansong** [comment]
I think they are still helpful. I'd say let's keep them.

**Comment by b-sumner** [comment]
OK, then I'd suggest prefixing them with HW_ID_ and replacing BitSize with SIZE and BitOffset with OFFSET

**Comment by guansong** [comment]
Sounds good, I will change the code.

**Pull request merged**
