### PR TITLE
Set required minimum cmake version to LLVM's minimum cmake version

### PR DESCRIPTION
**Pull request by haampie**
I think this is an oversight

### CODE REVIEW

**Comment by haampie** [comment]
Pinging @b-sumner for a review

**Comment by b-sumner** [comment]
Thanks, this was definitely an oversight.    The fix should propagate here "soon".

**Comment by kzhuravl** [comment]
Is this still needed?

**Comment by kzhuravl** [comment]
Looks like the fix was already merged into amd-stg-open.

**Pull request closed without merging**
