### PR TITLE
Documentation change

### PR DESCRIPTION
**Pull request by whchung**
Inform users to build ROCm-Device-Libs with LLVM/LLD/Clang from
RadeonOpenCompute.

### CODE REVIEW

**Comment by nhaustov** [comment]
Can you change 'contains' to 'may contain'. Otherwise looks ok.

**Comment by whchung** [comment]
@nhaustov I revised README.md , plus I added one file for Kaveri (ISA version string 700). Could you review if it's ok? Thanks.

**Comment by whchung** [comment]
@b-sumner I reverted change to add Kaveri support. Could you review again? Thanks.

**Comment by b-sumner** [comment]
Thanks, this looks good to me.

**Pull request merged**
