### PR TITLE
More ignore files for git, sync with llvm/clang

### PR DESCRIPTION
**Pull request by guansong**

### CODE REVIEW

**Comment by b-sumner** [comment]
We haven't needed these before.  Is it really necessary?

**Comment by guansong** [comment]
It is useful for me when I have vim opened many files to shuffle things around. It is also a minor improvement over the project structure. We do not need it if you don't like it.

**Comment by b-sumner** [comment]
Would you mind reducing it to what you actually need?  I'm OK with growing it if it will actually be used.

**Comment by guansong** [comment]
close this for now, seems not much need by the group.

**Pull request closed without merging**
